FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Ставим nginx
RUN apk add --no-cache nginx

# Копируем собранные файлы (build)
RUN cp -r build/* /usr/share/nginx/html/

# Копируем nginx конфиг
COPY nginx.conf /etc/nginx/http.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
