# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile.prod
#     ports:
#       - "8080:80" # Связываем порт 8080 на хосте с портом 80 в контейнере (Nginx)
#     networks:
#       - backend_fool_game_network
#     environment:
#       - REACT_APP_BACKEND_HOST=app

# networks:
#   backend_fool_game_network:
#     external: true
